-- Fix user roles: adminFG@gmail.com should be admin, dugarvishal@gmail.com should be user
UPDATE public.profiles 
SET role = 'admin'::app_role 
WHERE email = 'adminfg@gmail.com';

UPDATE public.profiles 
SET role = 'user'::app_role 
WHERE email = 'dugarvishal@gmail.com';

-- Enhance chatbot knowledge base with comprehensive cybersecurity content
INSERT INTO public.chatbot_knowledge (question, answer, intent, category, keywords, confidence_threshold) VALUES

-- Advanced Phishing Detection
('What are advanced phishing techniques?', 'Advanced phishing techniques include: 1) **Spear Phishing** - Targeted attacks using personal information, 2) **Whaling** - Targeting high-profile executives, 3) **Clone Phishing** - Copying legitimate emails with malicious links, 4) **Pharming** - DNS manipulation to redirect users, 5) **Vishing** - Voice phishing via phone calls, 6) **Smishing** - SMS-based phishing attacks. Always verify sender identity through separate communication channels.', 'threat_education', 'security', ARRAY['phishing', 'spear phishing', 'whaling', 'clone phishing', 'pharming', 'vishing', 'smishing', 'advanced threats'], 0.8),

-- Malware Analysis
('How do I identify malware indicators?', 'Key malware indicators include: 1) **Behavioral Signs** - Slow performance, unexpected pop-ups, unusual network activity, 2) **File Indicators** - Unknown processes, suspicious file extensions (.scr, .bat, .exe from unknown sources), 3) **Network Indicators** - Connections to suspicious IPs, unusual DNS requests, 4) **System Changes** - Modified registry entries, new startup programs, disabled security software. Use tools like Process Monitor and network analyzers for detection.', 'threat_analysis', 'security', ARRAY['malware', 'indicators', 'analysis', 'detection', 'behavioral', 'network activity', 'suspicious files'], 0.8),

-- Social Engineering
('What are common social engineering attacks?', 'Common social engineering attacks: 1) **Pretexting** - Creating false scenarios to gain trust, 2) **Baiting** - Offering something enticing to trigger action, 3) **Quid Pro Quo** - Offering service in exchange for information, 4) **Tailgating** - Following authorized users into secure areas, 5) **Authority Impersonation** - Posing as executives or IT staff, 6) **Urgency Tactics** - Creating false deadlines to pressure quick decisions. Always verify requests through established channels.', 'social_engineering', 'security', ARRAY['social engineering', 'pretexting', 'baiting', 'quid pro quo', 'tailgating', 'authority', 'urgency'], 0.8),

-- Financial Fraud
('How can I protect against financial fraud online?', 'Financial fraud protection strategies: 1) **Verify Legitimacy** - Check official website URLs, look for HTTPS, verify certificates, 2) **Banking Security** - Use official banking apps, never click email links to banking sites, enable 2FA, 3) **Investment Scams** - Be wary of guaranteed returns, verify investment platforms with regulators, 4) **Payment Protection** - Use secure payment methods, avoid wire transfers to unknown entities, 5) **Monitor Accounts** - Regular statement reviews, set up fraud alerts, use credit monitoring services.', 'fraud_prevention', 'security', ARRAY['financial fraud', 'banking security', 'investment scams', 'payment protection', 'fraud alerts'], 0.8),

-- Zero-day and APTs
('What are zero-day threats and APTs?', 'Zero-day threats exploit unknown vulnerabilities before patches are available. **APTs (Advanced Persistent Threats)** are sophisticated, long-term attacks by well-resourced adversaries. Protection strategies: 1) **Defense in Depth** - Multiple security layers, 2) **Behavioral Analysis** - Monitor for unusual patterns, 3) **Threat Intelligence** - Stay informed about emerging threats, 4) **Incident Response** - Have rapid response plans, 5) **Regular Updates** - Keep all systems patched, 6) **Network Segmentation** - Limit attack spread potential.', 'advanced_threats', 'security', ARRAY['zero-day', 'APT', 'advanced persistent threats', 'unknown vulnerabilities', 'behavioral analysis'], 0.9),

-- Incident Response
('What steps should I take during a security incident?', 'Security incident response steps: 1) **Identification** - Detect and confirm the incident, document initial findings, 2) **Containment** - Isolate affected systems, prevent spread, preserve evidence, 3) **Eradication** - Remove malware, close vulnerabilities, update security measures, 4) **Recovery** - Restore systems, monitor for recurring issues, validate security, 5) **Lessons Learned** - Document incident, update procedures, conduct training. Contact authorities if required and notify stakeholders appropriately.', 'incident_response', 'security', ARRAY['incident response', 'security incident', 'containment', 'eradication', 'recovery', 'lessons learned'], 0.8),

-- Compliance Requirements
('What are key cybersecurity compliance requirements?', 'Major compliance frameworks: 1) **GDPR** - EU data protection, requires consent, data minimization, breach notification, 2) **CCPA** - California privacy rights, data disclosure requirements, 3) **HIPAA** - Healthcare data protection, encryption requirements, 4) **SOX** - Financial reporting controls, IT governance, 5) **PCI DSS** - Payment card data security standards, 6) **ISO 27001** - Information security management systems. Each has specific technical and organizational requirements for data protection.', 'compliance', 'security', ARRAY['GDPR', 'CCPA', 'HIPAA', 'SOX', 'PCI DSS', 'ISO 27001', 'compliance', 'data protection'], 0.8),

-- Mobile Security
('What are mobile security best practices?', 'Mobile security essentials: 1) **App Security** - Download from official stores only, review permissions carefully, avoid suspicious apps, 2) **Device Security** - Enable lock screens, use biometric authentication, enable remote wipe, 3) **Network Security** - Avoid public WiFi for sensitive activities, use VPN, verify network names, 4) **Data Protection** - Enable encryption, regular backups, limit sensitive data storage, 5) **Update Management** - Install OS updates promptly, keep apps updated, remove unused applications.', 'mobile_security', 'security', ARRAY['mobile security', 'app permissions', 'device encryption', 'public wifi', 'mobile VPN', 'app store'], 0.8),

-- IoT Security
('How do I secure IoT devices?', 'IoT security measures: 1) **Default Settings** - Change default passwords immediately, disable unnecessary features, 2) **Network Segmentation** - Separate IoT devices from main network, use dedicated IoT networks, 3) **Regular Updates** - Enable auto-updates when available, monitor for firmware updates, 4) **Access Control** - Implement strong authentication, limit device permissions, 5) **Monitoring** - Monitor device behavior, watch for unusual network activity, 6) **Vendor Selection** - Choose reputable manufacturers with security track records.', 'iot_security', 'security', ARRAY['IoT security', 'default passwords', 'network segmentation', 'firmware updates', 'device monitoring'], 0.8),

-- Cryptocurrency Security
('How can I protect against cryptocurrency fraud?', 'Cryptocurrency fraud protection: 1) **Wallet Security** - Use hardware wallets for large amounts, secure seed phrases offline, enable 2FA, 2) **Exchange Safety** - Use reputable exchanges, enable withdrawal confirmations, don''t leave funds on exchanges, 3) **Scam Recognition** - Avoid guaranteed returns promises, verify project legitimacy, beware of pump-and-dump schemes, 4) **Transaction Verification** - Double-check addresses, understand transaction fees, verify smart contracts, 5) **Privacy Protection** - Use privacy coins carefully, understand regulatory implications.', 'crypto_security', 'security', ARRAY['cryptocurrency', 'crypto fraud', 'wallet security', 'exchange safety', 'seed phrase', 'hardware wallet'], 0.8),

-- Password Security
('What makes a strong password policy?', 'Strong password policy elements: 1) **Complexity Requirements** - Minimum 12 characters, mix of uppercase, lowercase, numbers, symbols, 2) **Uniqueness** - Different passwords for each account, avoid personal information, 3) **Password Managers** - Use reputable password managers, enable auto-generation, 4) **Multi-Factor Authentication** - Enable 2FA/MFA wherever possible, use authenticator apps over SMS, 5) **Regular Updates** - Change passwords after breaches, periodic updates for sensitive accounts, 6) **Avoid Common Mistakes** - No dictionary words, avoid keyboard patterns, don''t share passwords.', 'password_security', 'security', ARRAY['password policy', 'strong passwords', 'password manager', '2FA', 'MFA', 'multi-factor authentication'], 0.8),

-- Network Security
('How do I secure my home network?', 'Home network security steps: 1) **Router Security** - Change default admin passwords, update firmware regularly, disable WPS, 2) **WiFi Protection** - Use WPA3 encryption, strong WiFi passwords, hide network names if desired, 3) **Access Control** - Enable MAC address filtering, set up guest networks, limit connected devices, 4) **Monitoring** - Regular security scans, monitor connected devices, check for unauthorized access, 5) **Firewall Configuration** - Enable router firewall, configure port blocking, monitor traffic logs.', 'network_security', 'security', ARRAY['home network', 'router security', 'WiFi security', 'WPA3', 'firewall', 'network monitoring'], 0.8),

-- Data Backup and Recovery
('What is a proper data backup strategy?', 'Effective backup strategy (3-2-1 Rule): 1) **Three Copies** - Original data plus two backups, 2) **Two Different Media** - Use different storage types (cloud, external drives), 3) **One Offsite** - Keep one backup in different location, 4) **Regular Testing** - Test restore procedures regularly, verify backup integrity, 5) **Automation** - Set up automatic backups, schedule regular intervals, 6) **Encryption** - Encrypt sensitive backup data, secure backup storage, 7) **Version Control** - Keep multiple backup versions, define retention policies.', 'backup_strategy', 'security', ARRAY['data backup', '3-2-1 rule', 'backup strategy', 'disaster recovery', 'backup testing', 'encrypted backups'], 0.8),

-- Email Security
('How can I improve my email security?', 'Email security improvements: 1) **Authentication** - Enable 2FA on email accounts, use strong passwords, 2) **Phishing Protection** - Verify sender identity, don''t click suspicious links, check URLs carefully, 3) **Encryption** - Use encrypted email services, encrypt sensitive attachments, 4) **Spam Filtering** - Enable advanced spam filters, report spam messages, 5) **Safe Practices** - Don''t download unexpected attachments, verify forwarded messages, use BCC for group emails, 6) **Account Monitoring** - Review sent items regularly, check for unauthorized access, monitor login locations.', 'email_security', 'security', ARRAY['email security', 'phishing protection', 'encrypted email', 'spam filtering', 'email authentication'], 0.8),

-- Web Browser Security
('How do I browse the web safely?', 'Safe browsing practices: 1) **Browser Updates** - Keep browsers updated, enable automatic updates, 2) **Extension Security** - Only install trusted extensions, review permissions, remove unused extensions, 3) **Privacy Settings** - Configure privacy settings, disable tracking, clear cookies regularly, 4) **Safe Downloads** - Only download from trusted sources, scan downloads with antivirus, 5) **HTTPS Usage** - Look for HTTPS on sensitive sites, verify SSL certificates, 6) **Private Browsing** - Use incognito mode for sensitive sessions, understand limitations.', 'browser_security', 'security', ARRAY['browser security', 'safe browsing', 'HTTPS', 'browser extensions', 'private browsing', 'SSL certificates'], 0.8)